// <auto-generated />
using System;
using Metafar.ATM.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metafar.ATM.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20240822120808_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Account.AccountEntity", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FailedLoginAttempts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MaxLoginAttempts")
                        .HasColumnType("tinyint");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountNumber");

                    b.HasIndex("UserId");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = "33294946862678791686",
                            Balance = 1000m,
                            Blocked = false,
                            CardNumber = "3716774812566768",
                            FailedLoginAttempts = (byte)0,
                            MaxLoginAttempts = (byte)4,
                            Pin = "1111",
                            UserId = new Guid("b3b6f399-4993-42de-8772-9ae8a732504d")
                        },
                        new
                        {
                            AccountNumber = "57580242539941657006",
                            Balance = 50000m,
                            Blocked = false,
                            CardNumber = "3716745896852693",
                            FailedLoginAttempts = (byte)0,
                            MaxLoginAttempts = (byte)4,
                            Pin = "5555",
                            UserId = new Guid("774b7fa6-50fd-4abc-80f7-b2000b349c23")
                        },
                        new
                        {
                            AccountNumber = "68983408175964235159",
                            Balance = 100000m,
                            Blocked = false,
                            CardNumber = "3716485698515478",
                            FailedLoginAttempts = (byte)0,
                            MaxLoginAttempts = (byte)4,
                            Pin = "9999",
                            UserId = new Guid("4c7c5b69-d92e-44c4-8524-abe0a229779a")
                        });
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Transaction.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b98c3d44-d31b-4dd4-a90b-b4f7a94f55d6"),
                            AccountNumber = "33294946862678791686",
                            Amount = 50m,
                            TransactionDate = new DateTime(2024, 8, 2, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3111),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("a19e51bb-d427-4911-bb00-a16bddcf7ed1"),
                            AccountNumber = "33294946862678791686",
                            Amount = 100m,
                            TransactionDate = new DateTime(2024, 8, 2, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3129),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("132c5914-10bf-46de-b1fe-6ec966759442"),
                            AccountNumber = "33294946862678791686",
                            Amount = 100m,
                            TransactionDate = new DateTime(2024, 8, 3, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3131),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("65760a63-26b8-4b6c-9368-dc3f29e5fb98"),
                            AccountNumber = "33294946862678791686",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 4, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3134),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("4dc2abee-71b1-4b56-84e5-b0bb71a87ea9"),
                            AccountNumber = "33294946862678791686",
                            Amount = 750m,
                            TransactionDate = new DateTime(2024, 8, 5, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3137),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("c660d4f4-539d-442e-acdb-4ac5e33611bf"),
                            AccountNumber = "33294946862678791686",
                            Amount = 2000m,
                            TransactionDate = new DateTime(2024, 8, 5, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3140),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("db10b31f-3641-473c-b238-0bd6d3a883a5"),
                            AccountNumber = "33294946862678791686",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 6, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3142),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("7d0e15c9-de77-4a61-8294-d4eb23d2cd7c"),
                            AccountNumber = "33294946862678791686",
                            Amount = 500m,
                            TransactionDate = new DateTime(2024, 8, 7, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3144),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("a8701937-e4ff-4330-8e09-eb93ee884a3f"),
                            AccountNumber = "33294946862678791686",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3146),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("0cf6bf42-cc5b-48ab-dfde-08dcc2959449"),
                            AccountNumber = "57580242539941657006",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 2, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3148),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("c8937602-d923-47a4-dfdd-08dcc2959449"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 2, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3150),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("28257e7c-4b50-4f57-ea6a-08dcc294f655"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 3, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3152),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("00dfb276-131f-4698-ea69-08dcc294f655"),
                            AccountNumber = "57580242539941657006",
                            Amount = 1000m,
                            TransactionDate = new DateTime(2024, 8, 3, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3154),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("c1634965-4447-4caf-b2fb-77d4a461a139"),
                            AccountNumber = "57580242539941657006",
                            Amount = 500m,
                            TransactionDate = new DateTime(2024, 8, 4, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3156),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("9b32cebc-6e82-4481-9719-8fb989dbc89f"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 5, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3158),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("54442d6f-80f0-4e19-90d5-e6ca1198c891"),
                            AccountNumber = "57580242539941657006",
                            Amount = 2100m,
                            TransactionDate = new DateTime(2024, 8, 5, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3160),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("1ba6b48d-d481-49e0-9d7e-605ec6a7914a"),
                            AccountNumber = "57580242539941657006",
                            Amount = 500m,
                            TransactionDate = new DateTime(2024, 8, 5, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3162),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("652d4f5f-c122-4630-a14c-7cce1855949c"),
                            AccountNumber = "57580242539941657006",
                            Amount = 10000m,
                            TransactionDate = new DateTime(2024, 8, 6, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3163),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("122cb712-1867-4ac6-9e83-daef582e7f3f"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 6, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3165),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("4aed7169-34eb-42d4-9af9-5891dfa23d1a"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 7, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3167),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("0da4c8ab-9b1f-4856-a168-7f7299c50bb9"),
                            AccountNumber = "57580242539941657006",
                            Amount = 600m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3169),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("c4179123-bedd-4f8e-9c78-b4e30b2d4cbe"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3171),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("18b39627-c344-4b86-87a5-9d19b105426c"),
                            AccountNumber = "57580242539941657006",
                            Amount = 6000m,
                            TransactionDate = new DateTime(2024, 8, 9, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3173),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("0eacca6e-2b4c-4291-a4d0-3bba1a8c5813"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 10, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3175),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("4f89cc9e-ac64-4f02-b661-d801702c3e00"),
                            AccountNumber = "57580242539941657006",
                            Amount = 1000m,
                            TransactionDate = new DateTime(2024, 8, 10, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3177),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("fa36a108-245d-4602-9b97-886354e2971e"),
                            AccountNumber = "57580242539941657006",
                            Amount = 21000m,
                            TransactionDate = new DateTime(2024, 8, 11, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3179),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("346ba847-196a-4952-a169-7d45e48ca3ae"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 11, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3181),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("6883834d-a4df-414c-a8bd-ea658079d4c8"),
                            AccountNumber = "57580242539941657006",
                            Amount = 5000m,
                            TransactionDate = new DateTime(2024, 8, 12, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3183),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("2ac726dd-ef3a-4e78-893d-e142b2d8f3d8"),
                            AccountNumber = "57580242539941657006",
                            Amount = 10000m,
                            TransactionDate = new DateTime(2024, 8, 13, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3185),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("5cbe5a42-2914-4a4d-9895-77ad9ee3c409"),
                            AccountNumber = "57580242539941657006",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 14, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3187),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("2cc64ccd-78fa-47da-a0cc-bca20b3d803c"),
                            AccountNumber = "68983408175964235159",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 2, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3189),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("7bc2ab9f-b47f-4fb1-ac0b-c905accbfef6"),
                            AccountNumber = "68983408175964235159",
                            Amount = 100m,
                            TransactionDate = new DateTime(2024, 8, 3, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3190),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("8def9510-88b2-4ebf-ba85-6b73cd2a2356"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 4, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3192),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("2bd503e2-692d-4506-8b47-3452822b986b"),
                            AccountNumber = "68983408175964235159",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 6, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3194),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("d8e52a48-70ea-44a2-b8a8-325d5120aed9"),
                            AccountNumber = "68983408175964235159",
                            Amount = 5700m,
                            TransactionDate = new DateTime(2024, 8, 7, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3196),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("dfc616d7-dd3e-4a79-99b8-fce3c4afd480"),
                            AccountNumber = "68983408175964235159",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3198),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("d7b96d01-fdaf-43f6-97d5-fd0bba0941dc"),
                            AccountNumber = "68983408175964235159",
                            Amount = 100m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3200),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("2d32e29e-d95f-4a34-9498-369c6b0353e5"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 8, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3202),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("d74f7fa1-fbf4-4516-9cf8-05215487a55a"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 9, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3204),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("677ae7d1-f93c-412f-b944-0aaad2580f3a"),
                            AccountNumber = "68983408175964235159",
                            Amount = 5700m,
                            TransactionDate = new DateTime(2024, 8, 9, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3206),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("a199af2c-0d5b-4bdd-b74e-1ceba5afd680"),
                            AccountNumber = "68983408175964235159",
                            Amount = 100m,
                            TransactionDate = new DateTime(2024, 8, 10, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3208),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("6a4da6ac-8cd6-4c53-a96a-af1525fddfb0"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 11, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3210),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("99891c4a-d4b1-4dca-b865-7ae0b81927cc"),
                            AccountNumber = "68983408175964235159",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 11, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3212),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("05334834-9da0-48c5-8fae-406d030e2bbd"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 13, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3214),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("d0e74669-040d-4f99-8e71-f58db535803d"),
                            AccountNumber = "68983408175964235159",
                            Amount = 7000m,
                            TransactionDate = new DateTime(2024, 8, 13, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3215),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("52945988-3e34-440f-a8ce-add7265feb3f"),
                            AccountNumber = "68983408175964235159",
                            Amount = 500m,
                            TransactionDate = new DateTime(2024, 8, 14, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3217),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        },
                        new
                        {
                            Id = new Guid("f45e00c6-7d24-48d1-9451-8d82d4a33079"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 15, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3219),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("f53b4c16-6e95-4cb7-b921-18b1e99e6d79"),
                            AccountNumber = "68983408175964235159",
                            Amount = 150m,
                            TransactionDate = new DateTime(2024, 8, 16, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3221),
                            TransactionTypeId = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b")
                        },
                        new
                        {
                            Id = new Guid("f9ae8ced-fe3e-45fe-b871-ede0d75a2c5f"),
                            AccountNumber = "68983408175964235159",
                            Amount = 0m,
                            TransactionDate = new DateTime(2024, 8, 18, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3223),
                            TransactionTypeId = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18")
                        },
                        new
                        {
                            Id = new Guid("f4e41662-9661-40a8-93ab-54c921b050b5"),
                            AccountNumber = "68983408175964235159",
                            Amount = 5700m,
                            TransactionDate = new DateTime(2024, 8, 21, 9, 8, 8, 419, DateTimeKind.Local).AddTicks(3225),
                            TransactionTypeId = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e")
                        });
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Transaction.TransactionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f79ca38a-d81e-4c51-9b5f-741626a6ba18"),
                            TransactionType = "CHECKBALANCE"
                        },
                        new
                        {
                            Id = new Guid("9ec43875-4446-4f52-8daa-967c2d938c7b"),
                            TransactionType = "WITHDRAW"
                        },
                        new
                        {
                            Id = new Guid("4142de52-7053-478b-804b-b6bfa4217f1e"),
                            TransactionType = "DEPOSIT"
                        });
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b6f399-4993-42de-8772-9ae8a732504d"),
                            UserName = "John Smith"
                        },
                        new
                        {
                            Id = new Guid("4c7c5b69-d92e-44c4-8524-abe0a229779a"),
                            UserName = "Denzel Washington"
                        },
                        new
                        {
                            Id = new Guid("774b7fa6-50fd-4abc-80f7-b2000b349c23"),
                            UserName = "Johnny Depp"
                        });
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Account.AccountEntity", b =>
                {
                    b.HasOne("Metafar.ATM.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Transaction.TransactionEntity", b =>
                {
                    b.HasOne("Metafar.ATM.Domain.Entities.Account.AccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metafar.ATM.Domain.Entities.Transaction.TransactionTypeEntity", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.Account.AccountEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Metafar.ATM.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
